[package]
name = "generator"
version = "0.0.8"
edition = "2021"

[dependencies]
anyhow = "1.0"
proc-macro2 = "1.0"
syn = "2.0"
quick-xml = { version = "0.37", features = ["serialize"] }
serde = { version = "1.0", features = ["derive"] }
quote = "1.0"
