[package]
name = "vulkanite"
version = "0.0.10"
edition = "2021"
authors = ["Macdu <Macdu@users.noreply.github.com>"]
description = "Vulkan bindings for Rust"
license = "MIT OR Apache-2.0"
readme = "../README.md"
repository = "https://github.com/Macdu/vulkanite"
keywords = ["gamedev", "graphics", "vulkan", "bindings"]
categories = [
    "api-bindings",
    "external-ffi-bindings",
    "game-development",
    "graphics",
    "rendering::graphics-api"
]
rust-version = "1.77"

[dependencies]
bitflags = "2.5"
libloading = { version = "0.8", optional = true }
smallvec = { version = "1.13", optional = true, features = ["const_generics"] }
arrayvec = { version = "0.7", optional = true }
raw-window-handle = { version = "0.6", optional = true }

[target.'cfg(any(target_os = "macos", target_os = "ios"))'.dependencies]
raw-window-metal = { version = "1.1", optional = true }

[package.metadata.docs.rs]
all-features = true

[features]
loaded = ["dep:libloading"]
smallvec = ["dep:smallvec"]
arrayvec = ["dep:arrayvec"]
raw-window-handle = [
    "dep:raw-window-handle", 
    "ext_surface", 
    "ext_win32_surface", 
    "ext_xlib_surface", 
    "ext_xcb_surface", 
    "ext_wayland_surface", 
    "ext_android_surface", 
    "ext_metal_surface", 
    "ext_ios_surface", 
    "ext_macos_surface"]

# Features below are automatically generated, do not edit them manually
version_1_1 = []
version_1_2 = ["version_1_1"]
version_1_3 = ["version_1_2"]
version_1_4 = ["version_1_3"]

ext_surface = []
ext_swapchain = []
ext_display = []
ext_display_swapchain = []
ext_xlib_surface = []
ext_xcb_surface = []
ext_wayland_surface = []
ext_android_surface = []
ext_win32_surface = []
ext_debug_report = []
ext_filter_cubic = []
ext_rasterization_order = []
ext_debug_marker = []
ext_dedicated_allocation = []
ext_transform_feedback = []
ext_binary_import = []
ext_image_view_handle = []
ext_draw_indirect_count = []
ext_shader_info = []
ext_dynamic_rendering = []
ext_stream_descriptor_surface = []
ext_multiview = []
ext_external_memory_capabilities = []
ext_external_memory = []
ext_external_memory_win32 = []
ext_win32_keyed_mutex = []
ext_get_physical_device_properties2 = []
ext_device_group = []
ext_validation_flags = []
ext_vi_surface = []
ext_astc_decode_mode = []
ext_pipeline_robustness = []
ext_maintenance1 = []
ext_device_group_creation = []
ext_external_memory_fd = []
ext_external_semaphore_capabilities = []
ext_external_semaphore = []
ext_external_semaphore_win32 = []
ext_external_semaphore_fd = []
ext_push_descriptor = []
ext_conditional_rendering = []
ext_incremental_present = []
ext_descriptor_update_template = []
ext_clip_space_w_scaling = []
ext_direct_mode_display = []
ext_acquire_xlib_display = []
ext_display_surface_counter = []
ext_display_control = []
ext_display_timing = []
ext_multiview_per_view_attributes = []
ext_viewport_swizzle = []
ext_discard_rectangles = []
ext_conservative_rasterization = []
ext_depth_clip_enable = []
ext_hdr_metadata = []
ext_imageless_framebuffer = []
ext_create_renderpass2 = []
ext_shared_presentable_image = []
ext_external_fence_capabilities = []
ext_external_fence = []
ext_external_fence_win32 = []
ext_external_fence_fd = []
ext_performance_query = []
ext_maintenance2 = []
ext_get_surface_capabilities2 = []
ext_get_display_properties2 = []
ext_ios_surface = []
ext_macos_surface = []
ext_debug_utils = []
ext_external_memory_android_hardware_buffer = []
ext_sampler_filter_minmax = []
ext_shader_enqueue = []
ext_mixed_attachment_samples = []
ext_inline_uniform_block = []
ext_sample_locations = []
ext_get_memory_requirements2 = []
ext_image_format_list = []
ext_blend_operation_advanced = []
ext_fragment_coverage_to_color = []
ext_acceleration_structure = []
ext_ray_tracing_pipeline = []
ext_framebuffer_mixed_samples = []
ext_sampler_ycbcr_conversion = []
ext_bind_memory2 = []
ext_image_drm_format_modifier = []
ext_validation_cache = []
ext_descriptor_indexing = []
ext_shading_rate_image = []
ext_ray_tracing = []
ext_representative_fragment_test = []
ext_maintenance3 = []
ext_global_priority = []
ext_external_memory_host = []
ext_buffer_marker = []
ext_pipeline_compiler_control = []
ext_calibrated_timestamps = []
ext_memory_overallocation_behavior = []
ext_vertex_attribute_divisor = []
ext_frame_token = []
ext_pipeline_creation_feedback = []
ext_driver_properties = []
ext_shader_float_controls = []
ext_depth_stencil_resolve = []
ext_mesh_shader = []
ext_scissor_exclusive = []
ext_device_diagnostic_checkpoints = []
ext_timeline_semaphore = []
ext_display_native_hdr = []
ext_imagepipe_surface = []
ext_metal_surface = []
ext_fragment_density_map = []
ext_subgroup_size_control = []
ext_fragment_shading_rate = []
ext_shader_core_properties2 = []
ext_dynamic_rendering_local_read = []
ext_memory_priority = []
ext_surface_protected_capabilities = []
ext_separate_depth_stencil_layouts = []
ext_buffer_device_address = []
ext_tooling_info = []
ext_separate_stencil_usage = []
ext_validation_features = []
ext_present_wait = []
ext_cooperative_matrix = []
ext_coverage_reduction_mode = []
ext_provoking_vertex = []
ext_full_screen_exclusive = []
ext_headless_surface = []
ext_line_rasterization = []
ext_host_query_reset = []
ext_extended_dynamic_state = []
ext_deferred_host_operations = []
ext_pipeline_executable_properties = []
ext_host_image_copy = []
ext_map_memory2 = []
ext_map_memory_placed = []
ext_surface_maintenance1 = []
ext_swapchain_maintenance1 = []
ext_device_generated_commands = []
ext_inherited_viewport_scissor = []
ext_render_pass_transform = []
ext_depth_bias_control = []
ext_device_memory_report = []
ext_acquire_drm_display = []
ext_custom_border_color = []
ext_pipeline_library = []
ext_present_barrier = []
ext_present_id = []
ext_private_data = []
ext_pipeline_creation_cache_control = []
ext_device_diagnostics_config = []
ext_cuda_kernel_launch = []
ext_tile_shading = []
ext_low_latency = []
ext_metal_objects = []
ext_synchronization2 = []
ext_descriptor_buffer = []
ext_graphics_pipeline_library = []
ext_fragment_shading_rate_enums = []
ext_ray_tracing_motion_blur = []
ext_rotated_copy_commands = []
ext_copy_commands2 = []
ext_image_compression_control = []
ext_device_fault = []
ext_rasterization_order_attachment_access = []
ext_acquire_winrt_display = []
ext_directfb_surface = []
ext_mutable_descriptor_type = []
ext_vertex_input_dynamic_state = []
ext_device_address_binding_report = []
ext_depth_clip_control = []
ext_format_feature_flags2 = []
ext_fuchsia_external_memory = []
ext_fuchsia_external_semaphore = []
ext_buffer_collection = []
ext_subpass_shading = []
ext_invocation_mask = []
ext_external_memory_rdma = []
ext_pipeline_properties = []
ext_frame_boundary = []
ext_multisampled_render_to_single_sampled = []
ext_extended_dynamic_state2 = []
ext_screen_surface = []
ext_color_write_enable = []
ext_ray_tracing_maintenance1 = []
ext_image_view_min_lod = []
ext_multi_draw = []
ext_opacity_micromap = []
ext_displacement_micromap = []
ext_cluster_culling_shader = []
ext_border_color_swizzle = []
ext_pageable_device_local_memory = []
ext_maintenance4 = []
ext_scheduling_controls = []
ext_image_sliced_view_of_3d = []
ext_descriptor_set_host_mapping = []
ext_render_pass_striped = []
ext_fragment_density_map_offset = []
ext_copy_memory_indirect = []
ext_memory_decompression = []
ext_device_generated_commands_compute = []
ext_ray_tracing_linear_swept_spheres = []
ext_image_processing = []
ext_external_memory_acquire_unmodified = []
ext_extended_dynamic_state3 = []
ext_subpass_merge_feedback = []
ext_direct_driver_loading = []
ext_tensors = []
ext_shader_module_identifier = []
ext_optical_flow = []
ext_maintenance5 = []
ext_anti_lag = []
ext_dense_geometry_format = []
ext_present_id2 = []
ext_present_wait2 = []
ext_shader_object = []
ext_pipeline_binary = []
ext_tile_properties = []
ext_amigo_profiling = []
ext_ray_tracing_invocation_reorder = []
ext_cooperative_vector = []
ext_layer_settings = []
ext_low_latency2 = []
ext_data_graph = []
ext_multiview_per_view_render_areas = []
ext_image_processing2 = []
ext_filter_cubic_weights = []
ext_ycbcr_degamma = []
ext_attachment_feedback_loop_dynamic_state = []
ext_unified_image_layouts = []
ext_external_memory_screen_buffer = []
ext_layered_driver = []
ext_maintenance6 = []
ext_tile_memory_heap = []
ext_display_stereo = []
ext_external_compute_queue = []
ext_maintenance7 = []
ext_cluster_acceleration_structure = []
ext_partitioned_acceleration_structure = []
ext_maintenance8 = []
ext_image_alignment_control = []
ext_depth_clamp_control = []
ext_maintenance9 = []
ext_ohos_surface = []
ext_hdr_vivid = []
ext_cooperative_matrix2 = []
ext_external_memory_metal = []
ext_fragment_density_map_layered = []
ext_present_metering = []
